# Generated by Django 4.2.7 on 2024-02-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_kind_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PeoductImages',
            new_name='ProductImages',
        ),
    ]
