# Generated by Django 4.2.7 on 2024-03-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_delivery_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='delivery',
            new_name='delivery_type',
        ),
    ]
