# Generated by Django 4.2.7 on 2024-03-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_delivery_product_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calendar_availability_date',
            field=models.CharField(default=1, max_length=55, verbose_name='Дата доступности продукта'),
            preserve_default=False,
        ),
    ]
