# Generated by Django 4.2.7 on 2024-03-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_name_alter_kind_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calendar_availability_date',
            field=models.DateTimeField(verbose_name='Дата доступности продукта'),
        ),
    ]
