# Generated by Django 4.2.7 on 2024-03-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_calendar_availability_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Локация продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='calendar_availability_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата доступности продукта'),
        ),
    ]
