# Generated by Django 4.2.7 on 2024-03-19 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_calendar_availability_date'),
        ('products', '0009_product_location_and_more'),
    ]

    operations = [
    ]
