# Generated by Django 4.2.7 on 2024-03-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_delivery_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Аллергены'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_price_per',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена доставки за/'),
        ),
        migrations.AddField(
            model_name='product',
            name='diet',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Диета'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_per',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена продукта за/'),
        ),
    ]
