# Generated by Django 4.2.7 on 2024-03-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_allergens_product_delivery_price_per_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_type',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Тип доставки'),
        ),
    ]
