# Generated by Django 4.2.7 on 2024-03-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calendar_availability_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доступности продукта'),
        ),
    ]
