# Generated by Django 4.2.7 on 2024-04-05 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0014_alter_product_calendar_availability_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО заказчика')),
                ('email', models.EmailField(max_length=254, verbose_name='почта заказчика')),
                ('number', models.CharField(max_length=255, verbose_name='Номер заказчика')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('add_service', models.CharField(max_length=255, verbose_name='Дополнительные услуги')),
                ('comment', models.CharField(max_length=255, verbose_name='Комментарии по поводу заказа')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_request_chef', to=settings.AUTH_USER_MODEL, verbose_name='Шеф')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_request_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (заказчик)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_request', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'История заказов',
                'verbose_name_plural': 'История заказов',
            },
        ),
    ]
