# Generated by Django 4.2.7 on 2024-04-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_productrequest_add_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrequest',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='productrequest',
            name='is_accept',
            field=models.BooleanField(default=False, verbose_name='Принять заказ'),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='is_refusal',
            field=models.BooleanField(default=False, verbose_name='Отказ'),
        ),
    ]
