# Generated by Django 4.2.7 on 2024-02-19 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Название магазина')),
                ('back_image', models.ImageField(blank=True, default='back_image/no_image.png', null=True, upload_to='back_image/', verbose_name='Фотография профиля')),
                ('location', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Подробное описание о вас')),
                ('design', models.CharField(blank=True, max_length=300, null=True, verbose_name='Дизайн профиля')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Редактор дизайна профиля',
                'verbose_name_plural': 'Редактор дизайна профиля',
            },
        ),
    ]
