# Generated by Django 4.2.7 on 2024-02-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_pages', '0002_alter_shop_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='back_image',
            field=models.ImageField(blank=True, default='back_image/no_image.png', null=True, upload_to='back_image/', verbose_name='Фото заднего фона на сайте'),
        ),
    ]
