# Generated by Django 4.2.7 on 2024-02-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_pages', '0004_alter_shop_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(verbose_name='Номер html документа')),
                ('image', models.ImageField(upload_to='design/', verbose_name='Фото дизайна')),
                ('full_image', models.ImageField(upload_to='design/', verbose_name='Полноё фото дизайна')),
            ],
            options={
                'verbose_name': 'Дизайн',
                'verbose_name_plural': 'Дизайны',
            },
        ),
    ]
