# Generated by Django 4.2.7 on 2024-03-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_pages', '0007_alter_shop_back_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=models.IntegerField(blank=True, max_length=300, null=True, verbose_name='Адрес'),
        ),
    ]
