# Generated by Django 5.0.1 on 2024-02-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=155, verbose_name='ФИО')),
                ('email', models.CharField(max_length=155, verbose_name='Адрес электронной почты')),
                ('number', models.CharField(max_length=75, verbose_name='Номер телефона')),
                ('message', models.CharField(max_length=355, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
