import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_banner', models.CharField(max_length=155, verbose_name='Заголовка баннера')),
                ('title_banner_en', models.CharField(max_length=155, null=True, verbose_name='Заголовка баннера')),
                ('title_banner_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовка баннера')),
                ('description_banner', models.CharField(max_length=155, verbose_name='Описание баннера')),
                ('description_banner_en', models.CharField(max_length=155, null=True, verbose_name='Описание баннера')),
                ('description_banner_ru', models.CharField(max_length=155, null=True, verbose_name='Описание баннера')),
                ('image_banner', models.ImageField(blank=True, null=True, upload_to='background_images/', verbose_name='Изображение баннера')),
                ('image_banner_en', models.ImageField(blank=True, null=True, upload_to='background_images/', verbose_name='Изображение баннера')),
                ('image_banner_ru', models.ImageField(blank=True, null=True, upload_to='background_images/', verbose_name='Изображение баннера')),
                ('title_about', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('title_about_en', models.CharField(max_length=155, null=True, verbose_name='Заголовок')),
                ('title_about_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовок')),
                ('title_about2', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('title_about2_en', models.CharField(max_length=155, null=True, verbose_name='Заголовок')),
                ('title_about2_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовок')),
                ('title_about3', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('title_about3_en', models.CharField(max_length=155, null=True, verbose_name='Заголовок')),
                ('title_about3_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовок')),
                ('description_about', models.CharField(max_length=155, verbose_name='Описание баннера')),
                ('description_about_en', models.CharField(max_length=155, null=True, verbose_name='Описание баннера')),
                ('description_about_ru', models.CharField(max_length=155, null=True, verbose_name='Описание баннера')),
                ('description_about2', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('description_about2_en', models.CharField(max_length=155, null=True, verbose_name='Заголовок')),
                ('description_about2_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовок')),
                ('description_about3', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('description_about3_en', models.CharField(max_length=155, null=True, verbose_name='Заголовок')),
                ('description_about3_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Настройка о нас',
                'verbose_name_plural': 'Настройки о нас',
            },
        ),
        migrations.CreateModel(
            name='Become',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка')),
                ('title_en', models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка')),
                ('title_ru', models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка')),
                ('descriptions', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('descriptions_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('descriptions_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='become/', verbose_name='Фото')),
                ('image_en', models.ImageField(blank=True, null=True, upload_to='become/', verbose_name='Фото')),
                ('image_ru', models.ImageField(blank=True, null=True, upload_to='become/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Познакомьтесь с другими культурами ',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=155, verbose_name='ФИО')),
                ('last_name_en', models.CharField(max_length=155, null=True, verbose_name='ФИО')),
                ('last_name_ru', models.CharField(max_length=155, null=True, verbose_name='ФИО')),
                ('email', models.CharField(max_length=155, verbose_name='Адрес электронной почты')),
                ('email_en', models.CharField(max_length=155, null=True, verbose_name='Адрес электронной почты')),
                ('email_ru', models.CharField(max_length=155, null=True, verbose_name='Адрес электронной почты')),
                ('number', models.CharField(max_length=75, verbose_name='Номер телефона')),
                ('number_en', models.CharField(max_length=75, null=True, verbose_name='Номер телефона')),
                ('number_ru', models.CharField(max_length=75, null=True, verbose_name='Номер телефона')),
                ('message', models.CharField(max_length=355, verbose_name='Сообщение')),
                ('message_en', models.CharField(max_length=355, null=True, verbose_name='Сообщение')),
                ('message_ru', models.CharField(max_length=355, null=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Gellary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовка')),
                ('image', models.ImageField(upload_to='gellary/', verbose_name='Фото')),
            ],
            options={
                'verbose_name_plural': 'Галлерия',
            },
        ),
        migrations.CreateModel(
            name='Hospitaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='Заголовка')),
                ('title_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовка')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('descriptions_en', models.TextField(null=True, verbose_name='Описание')),
                ('descriptions_ru', models.TextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='hospitaly', verbose_name='Фото')),
                ('image_en', models.ImageField(null=True, upload_to='hospitaly', verbose_name='Фото')),
                ('image_ru', models.ImageField(null=True, upload_to='hospitaly', verbose_name='Фото')),
                ('quests_title', models.CharField(max_length=155, verbose_name='Заголовка GUESTS ')),
                ('quests_title_en', models.CharField(max_length=155, null=True, verbose_name='Заголовка GUESTS ')),
                ('quests_title_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовка GUESTS ')),
                ('quests_all', ckeditor.fields.RichTextField(verbose_name='Описание 2')),
                ('quests_all_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание 2')),
                ('quests_all_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание 2')),
                ('quests_all2', ckeditor.fields.RichTextField(verbose_name='Описание 3')),
                ('quests_all2_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание 3')),
                ('quests_all2_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание 3')),
                ('quests_all3', ckeditor.fields.RichTextField(verbose_name='Описание 4')),
                ('quests_all3_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание 4')),
                ('quests_all3_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание 4')),
            ],
            options={
                'verbose_name_plural': 'ГОСТЕПРИИМСТВО',
            },
        ),
        migrations.CreateModel(
            name='Howitworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='Заголовка')),
                ('title_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовка')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('descriptions_en', models.TextField(null=True, verbose_name='Описание')),
                ('descriptions_ru', models.TextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='howitworks/')),
                ('image_en', models.ImageField(null=True, upload_to='howitworks/')),
                ('image_ru', models.ImageField(null=True, upload_to='howitworks/')),
                ('title2', models.CharField(max_length=155, verbose_name='Заголовка WORK')),
                ('title2_en', models.CharField(max_length=155, null=True, verbose_name='Заголовка WORK')),
                ('title2_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовка WORK')),
                ('title3', models.CharField(max_length=155, verbose_name='Заголовка 3')),
                ('title3_en', models.CharField(max_length=155, null=True, verbose_name='Заголовка 3')),
                ('title3_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовка 3')),
                ('title4', models.CharField(max_length=155, verbose_name='Заголовка 4')),
                ('title4_en', models.CharField(max_length=155, null=True, verbose_name='Заголовка 4')),
                ('title4_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовка 4')),
            ],
            options={
                'verbose_name_plural': 'Настройки всего Howitworks',
            },
        ),
        migrations.CreateModel(
            name='Perfect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='Заголовка')),
                ('title_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовка')),
                ('image', models.ImageField(upload_to='perfect/', verbose_name='Фото')),
                ('image_en', models.ImageField(null=True, upload_to='perfect/', verbose_name='Фото')),
                ('image_ru', models.ImageField(null=True, upload_to='perfect/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Найдите идеальную еду',
                'verbose_name_plural': 'Найдите идеальную еду ',
            },
        ),
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовок')),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('descriptions_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('descriptions_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Политика',
            },
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='Заголовка')),
                ('title_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовка')),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('descriptions_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('descriptions_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Конфедициально',
            },
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='rules_image_main/', verbose_name='Главная фотография')),
                ('main_image_en', models.ImageField(blank=True, null=True, upload_to='rules_image_main/', verbose_name='Главная фотография')),
                ('main_image_ru', models.ImageField(blank=True, null=True, upload_to='rules_image_main/', verbose_name='Главная фотография')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('description_en', models.CharField(max_length=255, null=True, verbose_name='Описание')),
                ('description_ru', models.CharField(max_length=255, null=True, verbose_name='Описание')),
                ('image1', models.ImageField(upload_to='image_rules1/', verbose_name='Фотография 1')),
                ('image1_en', models.ImageField(null=True, upload_to='image_rules1/', verbose_name='Фотография 1')),
                ('image1_ru', models.ImageField(null=True, upload_to='image_rules1/', verbose_name='Фотография 1')),
                ('flag1', models.ImageField(upload_to='flag_rules1/', verbose_name='Фото флага1')),
                ('flag1_en', models.ImageField(null=True, upload_to='flag_rules1/', verbose_name='Фото флага1')),
                ('flag1_ru', models.ImageField(null=True, upload_to='flag_rules1/', verbose_name='Фото флага1')),
                ('image2', models.ImageField(upload_to='image_rules2/', verbose_name='Фотография 2')),
                ('image2_en', models.ImageField(null=True, upload_to='image_rules2/', verbose_name='Фотография 2')),
                ('image2_ru', models.ImageField(null=True, upload_to='image_rules2/', verbose_name='Фотография 2')),
                ('flag2', models.ImageField(upload_to='flag_rules2/', verbose_name='Фото флага2')),
                ('flag2_en', models.ImageField(null=True, upload_to='flag_rules2/', verbose_name='Фото флага2')),
                ('flag2_ru', models.ImageField(null=True, upload_to='flag_rules2/', verbose_name='Фото флага2')),
                ('lottery_rule', ckeditor.fields.RichTextField(verbose_name='Правило')),
                ('lottery_rule_en', ckeditor.fields.RichTextField(null=True, verbose_name='Правило')),
                ('lottery_rule_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Правило')),
            ],
            options={
                'verbose_name': 'Правило',
                'verbose_name_plural': 'Правила',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовка')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовка')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовка')),
                ('descriptions', models.CharField(max_length=155, verbose_name='Описание')),
                ('descriptions_en', models.CharField(max_length=155, null=True, verbose_name='Описание')),
                ('descriptions_ru', models.CharField(max_length=155, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='settings/', verbose_name='Фото')),
                ('image_en', models.ImageField(null=True, upload_to='settings/', verbose_name='Фото')),
                ('image_ru', models.ImageField(null=True, upload_to='settings/', verbose_name='Фото')),
                ('become_title', models.CharField(max_length=155, verbose_name='Заголовка become ')),
                ('become_title_en', models.CharField(max_length=155, null=True, verbose_name='Заголовка become ')),
                ('become_title_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовка become ')),
                ('become_descriptions', models.TextField(max_length=300, verbose_name='Описание  become')),
                ('become_descriptions_en', models.TextField(max_length=300, null=True, verbose_name='Описание  become')),
                ('become_descriptions_ru', models.TextField(max_length=300, null=True, verbose_name='Описание  become')),
                ('become_button_text', models.CharField(max_length=50, verbose_name='Текст для button become')),
                ('become_button_text_en', models.CharField(max_length=50, null=True, verbose_name='Текст для button become')),
                ('become_button_text_ru', models.CharField(max_length=50, null=True, verbose_name='Текст для button become')),
                ('find_title', models.CharField(max_length=155, verbose_name='Заголовка find')),
                ('find_title_en', models.CharField(max_length=155, null=True, verbose_name='Заголовка find')),
                ('find_title_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовка find')),
                ('find_descriptions', models.CharField(max_length=255, verbose_name='Описание find')),
                ('find_descriptions_en', models.CharField(max_length=255, null=True, verbose_name='Описание find')),
                ('find_descriptions_ru', models.CharField(max_length=255, null=True, verbose_name='Описание find')),
                ('work_title', models.CharField(max_length=155, verbose_name='Заголовка work')),
                ('work_title_en', models.CharField(max_length=155, null=True, verbose_name='Заголовка work')),
                ('work_title_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовка work')),
                ('work_descriptions', models.CharField(max_length=255, verbose_name='Описание work')),
                ('work_descriptions_en', models.CharField(max_length=255, null=True, verbose_name='Описание work')),
                ('work_descriptions_ru', models.CharField(max_length=255, null=True, verbose_name='Описание work')),
                ('work_button_text', models.CharField(max_length=50, verbose_name='Текст для button work')),
                ('work_button_text_en', models.CharField(max_length=50, null=True, verbose_name='Текст для button work')),
                ('work_button_text_ru', models.CharField(max_length=50, null=True, verbose_name='Текст для button work')),
                ('download_title', models.CharField(max_length=155, verbose_name='Заголовка download')),
                ('download_title_en', models.CharField(max_length=155, null=True, verbose_name='Заголовка download')),
                ('download_title_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовка download')),
                ('download_descriptions', models.CharField(max_length=255, verbose_name='Описание download')),
                ('download_descriptions_en', models.CharField(max_length=255, null=True, verbose_name='Описание download')),
                ('download_descriptions_ru', models.CharField(max_length=255, null=True, verbose_name='Описание download')),
                ('host_title', models.CharField(max_length=155, verbose_name='Заголовка host')),
                ('host_title_en', models.CharField(max_length=155, null=True, verbose_name='Заголовка host')),
                ('host_title_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовка host')),
                ('host_button_text', models.CharField(max_length=50, verbose_name='Текст для button recommend')),
                ('host_button_text_en', models.CharField(max_length=50, null=True, verbose_name='Текст для button recommend')),
                ('host_button_text_ru', models.CharField(max_length=50, null=True, verbose_name='Текст для button recommend')),
                ('benefist_title', models.CharField(max_length=155, verbose_name='Заголовка benefist')),
                ('benefist_title_en', models.CharField(max_length=155, null=True, verbose_name='Заголовка benefist')),
                ('benefist_title_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовка benefist')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройки Главной страницы',
            },
        ),
        migrations.CreateModel(
            name='Specefic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='Заголовка')),
                ('title_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовка')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('descriptions_en', models.TextField(null=True, verbose_name='Описание')),
                ('descriptions_ru', models.TextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='specefic', verbose_name='Фото')),
                ('image_en', models.ImageField(null=True, upload_to='specefic', verbose_name='Фото')),
                ('image_ru', models.ImageField(null=True, upload_to='specefic', verbose_name='Фото')),
                ('title_about_diets', models.CharField(max_length=100, verbose_name='Заголовка О ДИЕТАХ')),
                ('title_about_diets_en', models.CharField(max_length=100, null=True, verbose_name='Заголовка О ДИЕТАХ')),
                ('title_about_diets_ru', models.CharField(max_length=100, null=True, verbose_name='Заголовка О ДИЕТАХ')),
                ('center', models.CharField(max_length=155, verbose_name='Центр')),
                ('center_en', models.CharField(max_length=155, null=True, verbose_name='Центр')),
                ('center_ru', models.CharField(max_length=155, null=True, verbose_name='Центр')),
                ('title_diets', ckeditor.fields.RichTextField(verbose_name='Заголовка diets ')),
                ('title_diets_en', ckeditor.fields.RichTextField(null=True, verbose_name='Заголовка diets ')),
                ('title_diets_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Заголовка diets ')),
                ('title_allergens', ckeditor.fields.RichTextField(verbose_name='Заголовка allergens ')),
                ('title_allergens_en', ckeditor.fields.RichTextField(null=True, verbose_name='Заголовка allergens ')),
                ('title_allergens_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Заголовка allergens ')),
                ('title_filters', ckeditor.fields.RichTextField(verbose_name='Заголовка filters ')),
                ('title_filters_en', ckeditor.fields.RichTextField(null=True, verbose_name='Заголовка filters ')),
                ('title_filters_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Заголовка filters ')),
                ('title_offered', ckeditor.fields.RichTextField(verbose_name='Заголовка offered ')),
                ('title_offered_en', ckeditor.fields.RichTextField(null=True, verbose_name='Заголовка offered ')),
                ('title_offered_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Заголовка offered ')),
                ('title_list', ckeditor.fields.RichTextField(verbose_name='Заголовка list ')),
                ('title_list_en', ckeditor.fields.RichTextField(null=True, verbose_name='Заголовка list ')),
                ('title_list_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Заголовка list ')),
            ],
            options={
                'verbose_name_plural': 'ОСОБЫЕ ОГРАНИЧЕНИЯ В ДИЕТЕ',
            },
        ),
        migrations.CreateModel(
            name='TrustSafety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_banner', models.CharField(max_length=155, verbose_name='Заголовок баннера')),
                ('title_banner_en', models.CharField(max_length=155, null=True, verbose_name='Заголовок баннера')),
                ('title_banner_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовок баннера')),
                ('description_banner', models.TextField(verbose_name='Описание баннера')),
                ('description_banner_en', models.TextField(null=True, verbose_name='Описание баннера')),
                ('description_banner_ru', models.TextField(null=True, verbose_name='Описание баннера')),
                ('background_image', models.ImageField(upload_to='background_images/', verbose_name='Изображение баннера')),
                ('background_image_en', models.ImageField(null=True, upload_to='background_images/', verbose_name='Изображение баннера')),
                ('background_image_ru', models.ImageField(null=True, upload_to='background_images/', verbose_name='Изображение баннера')),
                ('insurance_title', models.CharField(max_length=155, verbose_name='Заголовок Insurance')),
                ('insurance_title_en', models.CharField(max_length=155, null=True, verbose_name='Заголовок Insurance')),
                ('insurance_title_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовок Insurance')),
                ('insurance_description', models.TextField(verbose_name='Описание Insurance')),
                ('insurance_description_en', models.TextField(null=True, verbose_name='Описание Insurance')),
                ('insurance_description_ru', models.TextField(null=True, verbose_name='Описание Insurance')),
            ],
            options={
                'verbose_name': 'Доверие и Безопасность',
                'verbose_name_plural': 'Доверие и Безопасность',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='Заголовка')),
                ('title_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовка')),
                ('descriptions', models.CharField(max_length=255, verbose_name='Описание')),
                ('descriptions_en', models.CharField(max_length=255, null=True, verbose_name='Описание')),
                ('descriptions_ru', models.CharField(max_length=255, null=True, verbose_name='Описание')),
                ('icon', models.CharField(choices=[('Find a table', 'Find a table '), ('Make a reservation', 'Make a reservation'), ('Go to the rendezvous', 'Go to the rendezvous')], max_length=100, verbose_name='Иконку')),
                ('icon_en', models.CharField(choices=[('Find a table', 'Find a table '), ('Make a reservation', 'Make a reservation'), ('Go to the rendezvous', 'Go to the rendezvous')], max_length=100, null=True, verbose_name='Иконку')),
                ('icon_ru', models.CharField(choices=[('Find a table', 'Find a table '), ('Make a reservation', 'Make a reservation'), ('Go to the rendezvous', 'Go to the rendezvous')], max_length=100, null=True, verbose_name='Иконку')),
                ('forein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.become')),
            ],
            options={
                'verbose_name': 'Как это работает',
                'verbose_name_plural': 'Как это работает',
            },
        ),
        migrations.CreateModel(
            name='TrustSafetyObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_image', models.ImageField(upload_to='icons/', verbose_name='Иконка элемента')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок элемента')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='Заголовок элемента')),
                ('title_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовок элемента')),
                ('description', models.TextField(verbose_name='Описание элемента')),
                ('description_en', models.TextField(null=True, verbose_name='Описание элемента')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание элемента')),
                ('trustsafety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_trustsafety', to='base.trustsafety', verbose_name='Объект Trust')),
            ],
            options={
                'verbose_name': 'Доверие и Безопасность',
                'verbose_name_plural': 'Доверие и Безопасность',
            },
        ),
        migrations.CreateModel(
            name='PerfectActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка')),
                ('title_en', models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка')),
                ('title_ru', models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='perfect', verbose_name='Фото')),
                ('image_en', models.ImageField(blank=True, null=True, upload_to='perfect', verbose_name='Фото')),
                ('image_ru', models.ImageField(blank=True, null=True, upload_to='perfect', verbose_name='Фото')),
                ('title_price', models.CharField(max_length=155, verbose_name='Заголовка цены')),
                ('context_price', models.CharField(max_length=155, verbose_name='Описание цены')),
                ('title_price2', models.CharField(max_length=155, verbose_name='Заголовка цены 2')),
                ('context_price2', models.CharField(max_length=155, verbose_name='цены 2')),
                ('foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.perfect')),
            ],
            options={
                'verbose_name': 'Найдите идеальную еду Active',
                'verbose_name_plural': 'Найдите идеальную еду Active',
            },
        ),
        migrations.CreateModel(
            name='InsuranceObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=155, verbose_name='Вопрос Insurance')),
                ('question_en', models.CharField(max_length=155, null=True, verbose_name='Вопрос Insurance')),
                ('question_ru', models.CharField(max_length=155, null=True, verbose_name='Вопрос Insurance')),
                ('answer', models.TextField(verbose_name='Ответ Insurance')),
                ('answer_en', models.TextField(null=True, verbose_name='Ответ Insurance')),
                ('answer_ru', models.TextField(null=True, verbose_name='Ответ Insurance')),
                ('trustsafety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_trustsafety', to='base.trustsafety', verbose_name='Объект Insurance')),
            ],
            options={
                'verbose_name': 'Insurance',
                'verbose_name_plural': 'Insurance',
            },
        ),
        migrations.CreateModel(
            name='HowitworksObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='Заголовка')),
                ('title_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовка')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('descriptions_en', models.TextField(null=True, verbose_name='Описание')),
                ('descriptions_ru', models.TextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='howitworks/')),
                ('image_en', models.ImageField(null=True, upload_to='howitworks/')),
                ('image_ru', models.ImageField(null=True, upload_to='howitworks/')),
                ('foreing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.howitworks')),
            ],
            options={
                'verbose_name_plural': 'Объект Howitworks',
            },
        ),
        migrations.CreateModel(
            name='GuestsHosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='Заголовка')),
                ('title_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовка')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('descriptions_en', models.TextField(null=True, verbose_name='Описание')),
                ('descriptions_ru', models.TextField(null=True, verbose_name='Описание')),
                ('icon', models.CharField(choices=[('Find a publication', 'Find a publication'), ('Make a reservation with a host', 'Make a reservation with a host'), ('Go to your reservation', 'Go to your reservation'), ('Propose a meal', 'Propose a meal'), ('Handle your publications', 'Handle your publications'), ('Welcome your guests', 'Welcome your guests')], max_length=100, verbose_name='Иконка')),
                ('icon_en', models.CharField(choices=[('Find a publication', 'Find a publication'), ('Make a reservation with a host', 'Make a reservation with a host'), ('Go to your reservation', 'Go to your reservation'), ('Propose a meal', 'Propose a meal'), ('Handle your publications', 'Handle your publications'), ('Welcome your guests', 'Welcome your guests')], max_length=100, null=True, verbose_name='Иконка')),
                ('icon_ru', models.CharField(choices=[('Find a publication', 'Find a publication'), ('Make a reservation with a host', 'Make a reservation with a host'), ('Go to your reservation', 'Go to your reservation'), ('Propose a meal', 'Propose a meal'), ('Handle your publications', 'Handle your publications'), ('Welcome your guests', 'Welcome your guests')], max_length=100, null=True, verbose_name='Иконка')),
                ('foreing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.howitworks')),
            ],
            options={
                'verbose_name_plural': 'Объект Howitworks 2',
            },
        ),
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовка')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Заголовка')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Заголовка')),
                ('image', models.ImageField(upload_to='settings/', verbose_name='Фото')),
                ('image_en', models.ImageField(null=True, upload_to='settings/', verbose_name='Фото')),
                ('image_ru', models.ImageField(null=True, upload_to='settings/', verbose_name='Фото')),
                ('locations', models.CharField(max_length=100, verbose_name='Локация')),
                ('locations_en', models.CharField(max_length=100, null=True, verbose_name='Локация')),
                ('locations_ru', models.CharField(max_length=100, null=True, verbose_name='Локация')),
                ('forein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.become')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Рекомендуемые хосты',
            },
        ),
        migrations.CreateModel(
            name='CookingActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='Заголовка')),
                ('title_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовка')),
                ('descriptions', models.CharField(max_length=200, verbose_name='Описание')),
                ('descriptions_en', models.CharField(max_length=200, null=True, verbose_name='Описание')),
                ('descriptions_ru', models.CharField(max_length=200, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='settings/', verbose_name='Фото')),
                ('image_en', models.ImageField(null=True, upload_to='settings/', verbose_name='Фото')),
                ('image_ru', models.ImageField(null=True, upload_to='settings/', verbose_name='Фото')),
                ('button_text', models.CharField(max_length=50, verbose_name='Текст для кнопки')),
                ('button_text_en', models.CharField(max_length=50, null=True, verbose_name='Текст для кнопки')),
                ('button_text_ru', models.CharField(max_length=50, null=True, verbose_name='Текст для кнопки')),
                ('forein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.become')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'ВСТРЕЧАТЬ НОВЫХ ЛЮДЕЙ Active',
            },
        ),
        migrations.CreateModel(
            name='Cooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='Заголовка')),
                ('title_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовка')),
                ('descriptions', models.CharField(max_length=200, verbose_name='Описание')),
                ('descriptions_en', models.CharField(max_length=200, null=True, verbose_name='Описание')),
                ('descriptions_ru', models.CharField(max_length=200, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='settings/', verbose_name='Фото')),
                ('image_en', models.ImageField(null=True, upload_to='settings/', verbose_name='Фото')),
                ('image_ru', models.ImageField(null=True, upload_to='settings/', verbose_name='Фото')),
                ('forein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.become')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'ВСТРЕЧАТЬ НОВЫХ ЛЮДЕЙ',
            },
        ),
        migrations.CreateModel(
            name='Benefist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='Заголовка')),
                ('title_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовка')),
                ('descriptions', models.CharField(max_length=200, verbose_name='Описание заголовка')),
                ('descriptions_en', models.CharField(max_length=200, null=True, verbose_name='Описание заголовка')),
                ('descriptions_ru', models.CharField(max_length=200, null=True, verbose_name='Описание заголовка')),
                ('context', models.CharField(max_length=155, verbose_name='описание')),
                ('context_en', models.CharField(max_length=155, null=True, verbose_name='описание')),
                ('context_ru', models.CharField(max_length=155, null=True, verbose_name='описание')),
                ('image', models.ImageField(upload_to='settings/', verbose_name='Фото')),
                ('image_en', models.ImageField(null=True, upload_to='settings/', verbose_name='Фото')),
                ('image_ru', models.ImageField(null=True, upload_to='settings/', verbose_name='Фото')),
                ('color', models.CharField(choices=[('User-friendly', 'User-friendly'), ('Feel like home', 'Feel like home'), ('An insured quality', 'An insured quality'), ('Authenticity', 'Authenticity')], max_length=100, verbose_name='Цвет')),
                ('color_en', models.CharField(choices=[('User-friendly', 'User-friendly'), ('Feel like home', 'Feel like home'), ('An insured quality', 'An insured quality'), ('Authenticity', 'Authenticity')], max_length=100, null=True, verbose_name='Цвет')),
                ('color_ru', models.CharField(choices=[('User-friendly', 'User-friendly'), ('Feel like home', 'Feel like home'), ('An insured quality', 'An insured quality'), ('Authenticity', 'Authenticity')], max_length=100, null=True, verbose_name='Цвет')),
                ('button_text', models.CharField(max_length=50, verbose_name='Текст для кнопки')),
                ('button_text_en', models.CharField(max_length=50, null=True, verbose_name='Текст для кнопки')),
                ('button_text_ru', models.CharField(max_length=50, null=True, verbose_name='Текст для кнопки')),
                ('forein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.become')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Преимущества домашней еды',
            },
        ),
        migrations.CreateModel(
            name='BecomeActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка')),
                ('title_en', models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка')),
                ('title_ru', models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка')),
                ('descriptions', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('descriptions_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('descriptions_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='become', verbose_name='Фото')),
                ('image_en', models.ImageField(blank=True, null=True, upload_to='become', verbose_name='Фото')),
                ('image_ru', models.ImageField(blank=True, null=True, upload_to='become', verbose_name='Фото')),
                ('forein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.become')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Познакомьтесь с другими культурами Active',
            },
        ),
    ]
