# Generated by Django 4.2.7 on 2024-02-14 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='become',
            name='parent_become',
        ),
    ]
