# Generated by Django 4.2.7 on 2024-02-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfectactive',
            name='context_price2_en',
            field=models.CharField(max_length=155, null=True, verbose_name='цены 2'),
        ),
        migrations.AddField(
            model_name='perfectactive',
            name='context_price2_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='цены 2'),
        ),
        migrations.AddField(
            model_name='perfectactive',
            name='context_price_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Описание цены'),
        ),
        migrations.AddField(
            model_name='perfectactive',
            name='context_price_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Описание цены'),
        ),
        migrations.AddField(
            model_name='perfectactive',
            name='title_price2_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовка цены 2'),
        ),
        migrations.AddField(
            model_name='perfectactive',
            name='title_price2_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовка цены 2'),
        ),
        migrations.AddField(
            model_name='perfectactive',
            name='title_price_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовка цены'),
        ),
        migrations.AddField(
            model_name='perfectactive',
            name='title_price_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовка цены'),
        ),
    ]
