# Generated by Django 5.0.1 on 2024-02-06 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Become',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('descriptions', models.CharField(max_length=255, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='become', verbose_name='Фото')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Познакомьтесь с другими культурами ',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовка')),
                ('descriptions', models.CharField(max_length=155, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='settings', verbose_name='Фото')),
                ('become_title', models.CharField(max_length=155, verbose_name='Заголовка - 2')),
                ('become_descriptions', models.TextField(max_length=300, verbose_name='Описание')),
                ('find_title', models.CharField(max_length=155, verbose_name='Заголовка - 3')),
                ('find_descriptions', models.CharField(max_length=255, verbose_name='Описание')),
                ('work_title', models.CharField(max_length=155, verbose_name='Заголовка - 5')),
                ('work_descriptions', models.CharField(max_length=255, verbose_name='Описание')),
                ('download_title', models.CharField(max_length=155, verbose_name='Заголовка - 6')),
                ('download_descriptions', models.CharField(max_length=255, verbose_name='Описание')),
                ('host_title', models.CharField(max_length=155, verbose_name='Заголовка - 7')),
                ('benefist_title', models.CharField(max_length=155, verbose_name='Заголовка - 8')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройки Главной страницы',
            },
        ),
        migrations.CreateModel(
            name='Benefist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.CharField(max_length=200, verbose_name='Описание заголовка')),
                ('context', models.CharField(max_length=155, verbose_name='описание')),
                ('image', models.ImageField(upload_to='settings', verbose_name='Фото')),
                ('title', models.ForeignKey(max_length=155, on_delete=django.db.models.deletion.CASCADE, to='base.become', verbose_name='Заголовка')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Преимущества домашней еды',
            },
        ),
        migrations.CreateModel(
            name='Cooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.CharField(max_length=200, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='settings', verbose_name='Фото')),
                ('title', models.ForeignKey(max_length=155, on_delete=django.db.models.deletion.CASCADE, to='base.become', verbose_name='Заголовка')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'ВСТРЕЧАТЬ НОВЫХ ЛЮДЕЙ',
            },
        ),
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='settings', verbose_name='Фото')),
                ('locations', models.CharField(max_length=100, verbose_name='Локация')),
                ('title', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='base.become', verbose_name='Заголовка')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Рекомендуемые хосты',
            },
        ),
        migrations.CreateModel(
            name='Perfect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='perfect', verbose_name='Фото')),
                ('title', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='base.become', verbose_name='Заголовка')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Найдите идеальную еду',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.CharField(max_length=255, verbose_name='Описание')),
                ('title', models.ForeignKey(max_length=155, on_delete=django.db.models.deletion.CASCADE, to='base.become', verbose_name='Заголовка')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Как это работает',
            },
        ),
    ]
