# Generated by Django 4.2.7 on 2024-02-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_become_parent_become'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='become_button_text',
            field=models.CharField(default=1, max_length=50, verbose_name='Текст для button'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='become_button_text_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Текст для button'),
        ),
        migrations.AddField(
            model_name='settings',
            name='become_button_text_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Текст для button'),
        ),
    ]
