# Generated by Django 4.2.7 on 2024-02-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_perfectactive_context_price2_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfectactive',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='perfect/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='perfectactive',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='perfect/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='perfectactive',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to='perfect/', verbose_name='Фото'),
        ),
    ]
