# Generated by Django 5.0.1 on 2024-02-06 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_perfect_options_alter_work_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='forein',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.become'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=155, verbose_name='Заголовка'),
        ),
    ]
