# Generated by Django 4.2.7 on 2024-02-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_settings_become_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefist',
            name='button_text',
            field=models.CharField(default=1, max_length=50, verbose_name='Текст для кнопки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='benefist',
            name='button_text_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Текст для кнопки'),
        ),
        migrations.AddField(
            model_name='benefist',
            name='button_text_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Текст для кнопки'),
        ),
        migrations.AddField(
            model_name='cookingactive',
            name='button_text',
            field=models.CharField(default=1, max_length=50, verbose_name='Текст для кнопки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cookingactive',
            name='button_text_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Текст для кнопки'),
        ),
        migrations.AddField(
            model_name='cookingactive',
            name='button_text_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Текст для кнопки'),
        ),
        migrations.AddField(
            model_name='settings',
            name='host_button_text',
            field=models.CharField(default=1, max_length=50, verbose_name='Текст для button recommend'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='host_button_text_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Текст для button recommend'),
        ),
        migrations.AddField(
            model_name='settings',
            name='host_button_text_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Текст для button recommend'),
        ),
        migrations.AddField(
            model_name='settings',
            name='work_button_text',
            field=models.CharField(default=1, max_length=50, verbose_name='Текст для button work'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='work_button_text_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Текст для button work'),
        ),
        migrations.AddField(
            model_name='settings',
            name='work_button_text_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Текст для button work'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='become_button_text',
            field=models.CharField(max_length=50, verbose_name='Текст для button become'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='become_button_text_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Текст для button become'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='become_button_text_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Текст для button become'),
        ),
    ]
