# Generated by Django 4.2.7 on 2024-02-18 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_guestshosts_icon_alter_guestshosts_icon_en_and_more'),
        ('base', '0003_alter_perfectactive_image_and_more'),
    ]

    operations = [
    ]
