# Generated by Django 4.2.7 on 2024-02-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_benefist_button_text_benefist_button_text_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gellary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовка')),
                ('image', models.ImageField(upload_to='gellary/', verbose_name='Фото')),
            ],
            options={
                'verbose_name_plural': 'Галлерия',
            },
        ),
    ]
