# Generated by Django 4.2.7 on 2024-03-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_merge_20240219_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='logo',
            field=models.ImageField(default=1, upload_to='logo/', verbose_name='Логотип сайта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='image',
            field=models.ImageField(upload_to='settings/', verbose_name='Фото заднего фона на главной странице'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='image_en',
            field=models.ImageField(null=True, upload_to='settings/', verbose_name='Фото заднего фона на главной странице'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='settings/', verbose_name='Фото заднего фона на главной странице'),
        ),
    ]
