# Generated by Django 4.2.7 on 2024-02-07 00:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_policies_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policies',
            name='descriptions',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='policies',
            name='title',
            field=models.CharField(max_length=155, verbose_name='Заголовок'),
        ),
    ]
