# Generated by Django 4.2.7 on 2024-02-07 00:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_policies_descriptions_alter_policies_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacy',
            name='descriptions',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
    ]
