# Generated by Django 4.2.7 on 2024-02-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_privacy_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='become_descriptions',
            field=models.TextField(max_length=300, verbose_name='Описание  become'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='become_title',
            field=models.CharField(max_length=155, verbose_name='Заголовка become '),
        ),
        migrations.AlterField(
            model_name='settings',
            name='benefist_title',
            field=models.CharField(max_length=155, verbose_name='Заголовка benefist'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='download_descriptions',
            field=models.CharField(max_length=255, verbose_name='Описание download'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='download_title',
            field=models.CharField(max_length=155, verbose_name='Заголовка download'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='find_descriptions',
            field=models.CharField(max_length=255, verbose_name='Описание find'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='find_title',
            field=models.CharField(max_length=155, verbose_name='Заголовка find'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='host_title',
            field=models.CharField(max_length=155, verbose_name='Заголовка host'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='work_descriptions',
            field=models.CharField(max_length=255, verbose_name='Описание work'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='work_descriptions2',
            field=models.CharField(max_length=255, verbose_name='Описание - 2 work'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='work_title',
            field=models.CharField(max_length=155, verbose_name='Заголовка work'),
        ),
    ]
