# Generated by Django 4.2.7 on 2024-02-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_work_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='become',
            name='descriptions',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='become',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='become', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='become',
            name='title',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка'),
        ),
    ]
