# Generated by Django 4.2.7 on 2024-02-10 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_become_descriptions_alter_become_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustSafety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_banner', models.CharField(max_length=155, verbose_name='Заголовок баннера')),
                ('description_banner', models.TextField(verbose_name='Описание баннера')),
                ('background_image', models.ImageField(upload_to='background_images/', verbose_name='Изображение баннера')),
                ('icon_image', models.ImageField(upload_to='icons/', verbose_name='Иконка элемента')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок элемента')),
                ('description', models.TextField(verbose_name='Описание элемента')),
                ('insurance_title', models.CharField(max_length=155, verbose_name='Заголовок Insurance')),
                ('insurance_description', models.TextField(verbose_name='Описание Insurance')),
            ],
            options={
                'verbose_name': 'Доверие и Безопасность',
                'verbose_name_plural': 'Доверие и Безопасность',
            },
        ),
        migrations.CreateModel(
            name='InsuranceObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=155, verbose_name='Вопрос Insurance')),
                ('answer', models.TextField(verbose_name='Ответ Insurance')),
                ('trustsafety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trustsafety', to='base.trustsafety', verbose_name='Объект Insurance')),
            ],
            options={
                'verbose_name': 'Доверие и Безопасность',
                'verbose_name_plural': 'Доверие и Безопасность',
            },
        ),
    ]
