# Generated by Django 4.2.7 on 2024-02-10 17:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_become_descriptions_alter_become_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='rules_image_main/', verbose_name='Главная фотография')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('image1', models.ImageField(upload_to='image_rules1/', verbose_name='Фотография 1')),
                ('flag1', models.ImageField(upload_to='flag_rules1/', verbose_name='Фото флага1')),
                ('image2', models.ImageField(upload_to='image_rules2/', verbose_name='Фотография 2')),
                ('flag2', models.ImageField(upload_to='flag_rules2/', verbose_name='Фото флага2')),
                ('lottery_rule', ckeditor.fields.RichTextField(verbose_name='Правило')),
            ],
            options={
                'verbose_name': 'Правило',
                'verbose_name_plural': 'Правила',
            },
        ),
    ]
