# Generated by Django 4.2.7 on 2024-02-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_about_alter_become_image_alter_benefist_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image_banner',
            field=models.ImageField(blank=True, null=True, upload_to='background_images/', verbose_name='Изображение баннера'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image_banner_en',
            field=models.ImageField(blank=True, null=True, upload_to='background_images/', verbose_name='Изображение баннера'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image_banner_ru',
            field=models.ImageField(blank=True, null=True, upload_to='background_images/', verbose_name='Изображение баннера'),
        ),
    ]
