# Generated by Django 4.2.7 on 2024-02-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='rules_image_main/', verbose_name='Главная фотография'),
        ),
    ]
