# Generated by Django 4.2.7 on 2024-02-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_settings_work_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='work_context',
            field=models.CharField(max_length=255, verbose_name='Описание work - 2'),
        ),
    ]
