# Generated by Django 4.2.7 on 2024-02-10 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_about_image_banner_alter_about_image_banner_en_and_more'),
        ('base', '0015_remove_trustsafety_description_and_more'),
    ]

    operations = [
    ]
