# Generated by Django 4.2.7 on 2024-02-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_becomeactive_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PErfectActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('image', models.ImageField(upload_to='perfect', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Найдите идеальную еду',
                'verbose_name_plural': 'Найдите идеальную еду Active',
            },
        ),
        migrations.RemoveField(
            model_name='perfect',
            name='forein',
        ),
    ]
