# Generated by Django 4.2.7 on 2024-02-11 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_perfectactive_remove_perfect_forein'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookingActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('descriptions', models.CharField(max_length=200, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='settings', verbose_name='Фото')),
                ('forein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.become')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'ВСТРЕЧАТЬ НОВЫХ ЛЮДЕЙ  Active',
            },
        ),
    ]
