# Generated by Django 4.2.7 on 2024-02-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_cookingactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefist',
            name='color',
            field=models.CharField(choices=[('User-friendly', 'User-friendly'), ('Feel like home', 'Feel like home'), ('An insured quality', 'An insured quality'), ('Authenticity', 'Authenticity')], default=1, max_length=100, verbose_name='Цвет'),
            preserve_default=False,
        ),
    ]
