# Generated by Django 4.2.7 on 2024-02-12 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_benefist_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfectactive',
            options={'verbose_name': 'Найдите идеальную еду Active', 'verbose_name_plural': 'Найдите идеальную еду Active'},
        ),
        migrations.AddField(
            model_name='perfectactive',
            name='foreign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.perfect'),
            preserve_default=False,
        ),
    ]
