# Generated by Django 4.2.7 on 2024-02-10 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_rules_main_image'),
        ('base', '0016_merge_20240211_0137'),
        ('base', '0019_benefist_color'),
    ]

    operations = [
    ]
