# Generated by Django 4.2.7 on 2024-02-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_rename_quests_all1_hospitaly_quests_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specefic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='specefic', verbose_name='Фото')),
                ('title_about_diets', models.CharField(max_length=100, verbose_name='Заголовка О ДИЕТАХ')),
                ('center', models.CharField(max_length=155, verbose_name='Центр')),
                ('title_diets', models.CharField(max_length=155, verbose_name='Заголовка diets ')),
                ('title_allergens', models.CharField(max_length=155, verbose_name='Заголовка allergens ')),
                ('title_filters', models.CharField(max_length=155, verbose_name='Заголовка filters ')),
                ('title_offered', models.CharField(max_length=155, verbose_name='Заголовка offered ')),
                ('title_list', models.CharField(max_length=155, verbose_name='Заголовка list ')),
            ],
            options={
                'verbose_name_plural': 'ОСОБЫЕ ОГРАНИЧЕНИЯ В ДИЕТЕ',
            },
        ),
    ]
