# Generated by Django 4.2.7 on 2024-02-13 01:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_specefic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specefic',
            name='title_allergens',
            field=ckeditor.fields.RichTextField(verbose_name='Заголовка allergens '),
        ),
        migrations.AlterField(
            model_name='specefic',
            name='title_diets',
            field=ckeditor.fields.RichTextField(verbose_name='Заголовка diets '),
        ),
        migrations.AlterField(
            model_name='specefic',
            name='title_filters',
            field=ckeditor.fields.RichTextField(verbose_name='Заголовка filters '),
        ),
        migrations.AlterField(
            model_name='specefic',
            name='title_list',
            field=ckeditor.fields.RichTextField(verbose_name='Заголовка list '),
        ),
        migrations.AlterField(
            model_name='specefic',
            name='title_offered',
            field=ckeditor.fields.RichTextField(verbose_name='Заголовка offered '),
        ),
    ]
