# Generated by Django 4.2.7 on 2024-02-13 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_specefic_title_allergens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Howitworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='howitworks/')),
                ('title2', models.CharField(max_length=155, verbose_name='Заголовка WORK')),
            ],
            options={
                'verbose_name_plural': 'Настройки всего Howitworks',
            },
        ),
        migrations.CreateModel(
            name='HowitworksObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='howitworks/')),
                ('foreing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.howitworks')),
            ],
            options={
                'verbose_name_plural': 'Объект Howitworks',
            },
        ),
        migrations.CreateModel(
            name='GuestsHosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('foreing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.howitworks')),
            ],
            options={
                'verbose_name_plural': 'Объект Howitworks 2',
            },
        ),
    ]
