# Generated by Django 4.2.7 on 2024-02-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_howitworks_howitworksobject_guestshosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestshosts',
            name='icon',
            field=models.CharField(choices=[('Find a publication', 'Find a publication'), ('Make a reservation with a host', 'Make a reservation with a host'), ('Go to your reservation', 'Go to your reservation'), ('Propose a meal', 'Propose a meal'), ('Handle your publications', 'Handle your publications'), ('Welcome your guests', 'Welcome your guests')], default=1, max_length=100, verbose_name='Иконка'),
            preserve_default=False,
        ),
    ]
