# Generated by Django 4.2.7 on 2024-02-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_guestshosts_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestshosts',
            name='title2',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовка 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guestshosts',
            name='title3',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовка 3'),
            preserve_default=False,
        ),
    ]
