# Generated by Django 4.2.7 on 2024-02-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_guestshosts_title2_guestshosts_title3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestshosts',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='guestshosts',
            name='title3',
        ),
        migrations.AddField(
            model_name='howitworks',
            name='title3',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовка 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='howitworks',
            name='title4',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовка 4'),
            preserve_default=False,
        ),
    ]
