# Generated by Django 4.2.7 on 2024-02-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_remove_guestshosts_title2_remove_guestshosts_title3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfectactive',
            name='context_price',
            field=models.CharField(default=1, max_length=155, verbose_name='Описание цены'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfectactive',
            name='context_price2',
            field=models.CharField(default=1, max_length=155, verbose_name='Описание цены 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfectactive',
            name='inline',
            field=models.CharField(default=1, max_length=155, verbose_name='Типы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfectactive',
            name='title_price',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовка цены'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfectactive',
            name='title_price2',
            field=models.CharField(default=1, max_length=155, verbose_name='Заголовка цены 2'),
            preserve_default=False,
        ),
    ]
