# Generated by Django 4.2.7 on 2024-02-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_merge_20240211_0217'),
        ('base', '0030_remove_guestshosts_title2_remove_guestshosts_title3_and_more'),
    ]

    operations = [
    ]
