# Generated by Django 4.2.7 on 2024-02-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_merge_20240212_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cookingactive',
            options={'verbose_name': '', 'verbose_name_plural': 'ВСТРЕЧАТЬ НОВЫХ ЛЮДЕЙ Active'},
        ),
        migrations.AlterModelOptions(
            name='insuranceobjects',
            options={'verbose_name': 'Insurance', 'verbose_name_plural': 'Insurance'},
        ),
        migrations.AlterModelOptions(
            name='perfect',
            options={'verbose_name': 'Найдите идеальную еду', 'verbose_name_plural': 'Найдите идеальную еду Active'},
        ),
        migrations.AlterField(
            model_name='cookingactive',
            name='image',
            field=models.ImageField(upload_to='settings/', verbose_name='Фото'),
        ),
    ]
