# Generated by Django 4.2.7 on 2024-02-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_perfectactive_context_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfectactive',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='perfect', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='perfectactive',
            name='title',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка'),
        ),
    ]
