# Generated by Django 4.2.7 on 2024-02-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_perfectactive_image_alter_perfectactive_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfect',
            name='image',
            field=models.ImageField(upload_to='perfect/', verbose_name='Фото'),
        ),
    ]
