# Generated by Django 4.2.7 on 2024-02-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_perfect_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfectactive',
            name='inline',
        ),
        migrations.AlterField(
            model_name='perfectactive',
            name='context_price2',
            field=models.CharField(max_length=155, verbose_name='цены 2'),
        ),
    ]
