# Generated by Django 4.2.7 on 2024-02-13 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_specefic_center_en_specefic_center_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='work_context',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='work_context_en',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='work_context_ru',
        ),
    ]
