# Generated by Django 4.2.7 on 2024-02-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_remove_perfectactive_inline_and_more'),
        ('base', '0037_guestshosts_descriptions_en_and_more'),
    ]

    operations = [
    ]
