# Generated by Django 4.2.7 on 2024-02-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_merge_20240214_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfectactive',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='perfect', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='perfectactive',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to='perfect', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='perfectactive',
            name='title_en',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка'),
        ),
        migrations.AlterField(
            model_name='perfectactive',
            name='title_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка'),
        ),
    ]
