# Generated by Django 4.2.7 on 2024-02-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.CharField(max_length=255, verbose_name='Админ'),
        ),
    ]
