# Generated by Django 4.2.7 on 2024-02-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_message_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.CharField(default='админ', max_length=255, verbose_name='Админcтрация'),
        ),
    ]
