# Generated by Django 4.2.7 on 2024-02-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name_alter_user_job_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatBooked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('descriptions', models.CharField(max_length=155, verbose_name='Описание')),
            ],
        ),
    ]
