# Generated by Django 4.2.7 on 2024-02-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_birthday_user_month_of_birth_user_year_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Роль пользователя'),
        ),
    ]
