# Generated by Django 4.2.7 on 2024-03-09 14:25

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=None, help_text='Обязательное поле. Не более 30 символов. Только буквы, цифры и @/./+/-/_.', max_length=30, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
