# Generated by Django 4.2.7 on 2024-03-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'Пользователь с таким именем пользователя уже существует.'}, max_length=254, null=True, unique=True, verbose_name='Почта'),
        ),
    ]
