# Generated by Django 5.0.1 on 2024-02-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=300, verbose_name='вопрос'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='value',
            field=models.CharField(max_length=300, verbose_name='ответ на вопрос'),
        ),
    ]
