# Generated by Django 5.0.1 on 2024-02-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_alter_questions_question_alter_questions_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='value',
        ),
        migrations.AddField(
            model_name='questions',
            name='answer',
            field=models.TextField(default=1, verbose_name='ответ на вопрос'),
            preserve_default=False,
        ),
    ]
