# Generated by Django 4.2.7 on 2024-02-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_remove_questions_value_questions_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='faq',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='faq',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='faq',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='ответ на вопрос'),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer_ru',
            field=models.TextField(null=True, verbose_name='ответ на вопрос'),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_en',
            field=models.CharField(max_length=300, null=True, verbose_name='вопрос'),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='вопрос'),
        ),
    ]
