# Generated by Django 4.2.7 on 2024-02-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderTranslationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_button', models.CharField(max_length=50, verbose_name='Кнопка смены языка')),
                ('language_button_en', models.CharField(max_length=50, null=True, verbose_name='Кнопка смены языка')),
                ('language_button_ru', models.CharField(max_length=50, null=True, verbose_name='Кнопка смены языка')),
                ('become_a_chef_button', models.CharField(max_length=50, verbose_name='Кнопка "Стать шефом"')),
                ('become_a_chef_button_en', models.CharField(max_length=50, null=True, verbose_name='Кнопка "Стать шефом"')),
                ('become_a_chef_button_ru', models.CharField(max_length=50, null=True, verbose_name='Кнопка "Стать шефом"')),
                ('sign_in', models.CharField(max_length=50, verbose_name='Зарегистрироваться')),
                ('sign_in_en', models.CharField(max_length=50, null=True, verbose_name='Зарегистрироваться')),
                ('sign_in_ru', models.CharField(max_length=50, null=True, verbose_name='Зарегистрироваться')),
                ('login', models.CharField(max_length=50, verbose_name='Login')),
                ('login_en', models.CharField(max_length=50, null=True, verbose_name='Login')),
                ('login_ru', models.CharField(max_length=50, null=True, verbose_name='Login')),
                ('messages', models.CharField(max_length=50, verbose_name='Сообщения')),
                ('messages_en', models.CharField(max_length=50, null=True, verbose_name='Сообщения')),
                ('messages_ru', models.CharField(max_length=50, null=True, verbose_name='Сообщения')),
                ('profile', models.CharField(max_length=50, verbose_name='Профиль')),
                ('profile_en', models.CharField(max_length=50, null=True, verbose_name='Профиль')),
                ('profile_ru', models.CharField(max_length=50, null=True, verbose_name='Профиль')),
                ('account_settings', models.CharField(max_length=50, verbose_name='Настройки профиля')),
                ('account_settings_en', models.CharField(max_length=50, null=True, verbose_name='Настройки профиля')),
                ('account_settings_ru', models.CharField(max_length=50, null=True, verbose_name='Настройки профиля')),
                ('logout', models.CharField(max_length=50, verbose_name=' "Logout"')),
                ('logout_en', models.CharField(max_length=50, null=True, verbose_name=' "Logout"')),
                ('logout_ru', models.CharField(max_length=50, null=True, verbose_name=' "Logout"')),
                ('new_event', models.CharField(max_length=50, verbose_name='Создание ивента')),
                ('new_event_en', models.CharField(max_length=50, null=True, verbose_name='Создание ивента')),
                ('new_event_ru', models.CharField(max_length=50, null=True, verbose_name='Создание ивента')),
                ('events_in_progress', models.CharField(max_length=50, verbose_name='Имеющиеся ивентов')),
                ('events_in_progress_en', models.CharField(max_length=50, null=True, verbose_name='Имеющиеся ивентов')),
                ('events_in_progress_ru', models.CharField(max_length=50, null=True, verbose_name='Имеющиеся ивентов')),
                ('performances', models.CharField(max_length=50, verbose_name='Блюда')),
                ('performances_en', models.CharField(max_length=50, null=True, verbose_name='Блюда')),
                ('performances_ru', models.CharField(max_length=50, null=True, verbose_name='Блюда')),
                ('demands', models.CharField(max_length=50, verbose_name='Demands')),
                ('demands_en', models.CharField(max_length=50, null=True, verbose_name='Demands')),
                ('demands_ru', models.CharField(max_length=50, null=True, verbose_name='Demands')),
                ('payments_in', models.CharField(max_length=50, verbose_name='Полученные платежи')),
                ('payments_in_en', models.CharField(max_length=50, null=True, verbose_name='Полученные платежи')),
                ('payments_in_ru', models.CharField(max_length=50, null=True, verbose_name='Полученные платежи')),
                ('reservations', models.CharField(max_length=50, verbose_name='Бронь')),
                ('reservations_en', models.CharField(max_length=50, null=True, verbose_name='Бронь')),
                ('reservations_ru', models.CharField(max_length=50, null=True, verbose_name='Бронь')),
                ('payments_out', models.CharField(max_length=50, verbose_name='Отправленные платежи')),
                ('payments_out_en', models.CharField(max_length=50, null=True, verbose_name='Отправленные платежи')),
                ('payments_out_ru', models.CharField(max_length=50, null=True, verbose_name='Отправленные платежи')),
            ],
            options={
                'verbose_name': 'Кнопка Header',
                'verbose_name_plural': 'Кнопки Header',
            },
        ),
    ]
