# Generated by Django 4.2.7 on 2024-02-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('includes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headertranslationmodel',
            name='espace_home',
            field=models.CharField(default=1, max_length=50, verbose_name='Вкладка Espace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headertranslationmodel',
            name='espace_home_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Вкладка Espace'),
        ),
        migrations.AddField(
            model_name='headertranslationmodel',
            name='espace_home_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Вкладка Espace'),
        ),
    ]
