# Generated by Django 4.2.7 on 2024-02-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BecomeaHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('descriptions', models.CharField(max_length=255, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='becomeahost/', verbose_name='Фото')),
                ('title2', models.CharField(max_length=155, verbose_name='Заголовок Выбора')),
                ('title3', models.CharField(max_length=155, verbose_name='Заголовка ХОЗЯИН')),
                ('title4', models.CharField(max_length=155, verbose_name='Заголовок Sing-in')),
                ('descriptions2', models.CharField(max_length=255, verbose_name='Описание Sing-in')),
                ('title5', models.CharField(max_length=155, verbose_name='заголовок reservation')),
                ('descriptions3', models.CharField(max_length=255, verbose_name='Описание reservation')),
                ('title6', models.CharField(max_length=155, verbose_name='Заголовок guests')),
                ('descriptions4', models.CharField(max_length=255, verbose_name='Описание guests')),
                ('title_end', models.CharField(max_length=155, verbose_name='Заголовка Chef ')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройки всего BecomeAHost',
            },
        ),
    ]
