# Generated by Django 4.2.7 on 2024-02-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChefRegister',
        ),
    ]
