# Generated by Django 4.2.7 on 2024-02-14 08:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='question_15',
            field=models.CharField(default=1, max_length=155, verbose_name='Укажите дату '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='question_16',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Условия установления даты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='question_17',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Страница Об условиях для гостей'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='question_18',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Стран'),
            preserve_default=False,
        ),
    ]
