# Generated by Django 4.2.7 on 2024-02-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefregister',
            name='question_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Местоположение'),
        ),
    ]
