# Generated by Django 4.2.7 on 2024-02-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_remove_host_question_10_remove_host_question_10_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='question_8',
            field=models.TextField(verbose_name='Дополнительные фотографии продукта'),
        ),
        migrations.AlterField(
            model_name='host',
            name='question_8_en',
            field=models.TextField(null=True, verbose_name='Дополнительные фотографии продукта'),
        ),
        migrations.AlterField(
            model_name='host',
            name='question_8_ru',
            field=models.TextField(null=True, verbose_name='Дополнительные фотографии продукта'),
        ),
    ]
