# Generated by Django 4.2.7 on 2024-02-14 09:26

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('host', '0003_alter_host_question_18'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name_plural': 'Управление страницой  < стать шефом > '},
        ),
        migrations.CreateModel(
            name='ChefRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.CharField(max_length=155, verbose_name='Тип услуги')),
                ('question_2', models.CharField(max_length=255, verbose_name='Тип кухни')),
                ('question_3', ckeditor.fields.RichTextField(verbose_name='Местоположение')),
                ('question_4', models.CharField(max_length=155, verbose_name='Дополнительные услуги')),
                ('question_5', models.CharField(max_length=155, verbose_name='Доставка заказа')),
                ('question_6', models.CharField(max_length=155, verbose_name='Соблюдение диеты')),
                ('question_7', models.CharField(max_length=155, verbose_name='Аллергены')),
                ('question_8', models.CharField(max_length=155, verbose_name='Гостей максимум')),
                ('question_9', models.CharField(max_length=155, verbose_name='Гостей минимум')),
                ('question_10', models.CharField(max_length=155, verbose_name='Сумма с гостей')),
                ('question_11', models.CharField(max_length=155, verbose_name='Дайте название вашему объявлению')),
                ('question_12', models.CharField(max_length=155, verbose_name='Напишите подробное описание объявления')),
                ('image_host', models.ImageField(upload_to='image_host/', verbose_name='фотография в объявлении')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chef_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Управление страницой  < стать шефом > ',
            },
        ),
    ]
