# Generated by Django 4.2.7 on 2024-02-14 18:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_alter_chefregister_question_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefregister',
            name='image_host_en',
            field=models.ImageField(blank=True, null=True, upload_to='image_host/', verbose_name='фотография в объявлении'),
        ),
        migrations.AddField(
            model_name='chefregister',
            name='image_host_ru',
            field=models.ImageField(blank=True, null=True, upload_to='image_host/', verbose_name='фотография в объявлении'),
        ),
        migrations.AddField(
            model_name='chefregister',
            name='question_10_en',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Сумма с гостей'),
        ),
        migrations.AddField(
            model_name='chefregister',
            name='question_10_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Сумма с гостей'),
        ),
        migrations.AddField(
            model_name='chefregister',
            name='question_11_en',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Дайте название вашему объявлению'),
        ),
        migrations.AddField(
            model_name='chefregister',
            name='question_11_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Дайте название вашему объявлению'),
        ),
        migrations.AddField(
            model_name='chefregister',
            name='question_12_en',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Напишите подробное описание объявления'),
        ),
        migrations.AddField(
            model_name='chefregister',
            name='question_12_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Напишите подробное описание объявления'),
        ),
        migrations.AddField(
            model_name='chefregister',
            name='question_1_en',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Тип услуги'),
        ),
        migrations.AddField(
            model_name='chefregister',
            name='question_1_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Тип услуги'),
        ),
        migrations.AddField(
            model_name='chefregister',
            name='question_2_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип кухни'),
        ),
        migrations.AddField(
            model_name='chefregister',
            name='question_2_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип кухни'),
        ),
        migrations.AddField(
            model_name='chefregister',
            name='question_3_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='chefregister',
            name='question_3_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='chefregister',
            name='question_4_en',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Дополнительные услуги'),
        ),
        migrations.AddField(
            model_name='chefregister',
            name='question_4_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Дополнительные услуги'),
        ),
        migrations.AddField(
            model_name='chefregister',
            name='question_5_en',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Доставка заказа'),
        ),
        migrations.AddField(
            model_name='chefregister',
            name='question_5_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Доставка заказа'),
        ),
        migrations.AddField(
            model_name='chefregister',
            name='question_6_en',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Соблюдение диеты'),
        ),
        migrations.AddField(
            model_name='chefregister',
            name='question_6_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Соблюдение диеты'),
        ),
        migrations.AddField(
            model_name='chefregister',
            name='question_7_en',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Аллергены'),
        ),
        migrations.AddField(
            model_name='chefregister',
            name='question_7_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Аллергены'),
        ),
        migrations.AddField(
            model_name='chefregister',
            name='question_8_en',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Гостей максимум'),
        ),
        migrations.AddField(
            model_name='chefregister',
            name='question_8_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Гостей максимум'),
        ),
        migrations.AddField(
            model_name='chefregister',
            name='question_9_en',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Гостей минимум'),
        ),
        migrations.AddField(
            model_name='chefregister',
            name='question_9_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Гостей минимум'),
        ),
        migrations.AddField(
            model_name='host',
            name='button_2_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Название кнопки (next)'),
        ),
        migrations.AddField(
            model_name='host',
            name='button_2_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Название кнопки (next)'),
        ),
        migrations.AddField(
            model_name='host',
            name='button_3_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Название кнопки (return)'),
        ),
        migrations.AddField(
            model_name='host',
            name='button_3_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Название кнопки (return)'),
        ),
        migrations.AddField(
            model_name='host',
            name='button_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Название кнопки (start)'),
        ),
        migrations.AddField(
            model_name='host',
            name='button_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Название кнопки (start)'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_10_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Сумма с гостей'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_10_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Сумма с гостей'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_11_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Дайте название вашему объявлению'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_11_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Дайте название вашему объявлению'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_12_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Напишите подробное описание объявления'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_12_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Напишите подробное описание объявления'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_13_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Добавьте фотографии в объявление'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_13_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Добавьте фотографии в объявление'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_14_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание о фотографии'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_14_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание о фотографии'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_15_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Укажите дату '),
        ),
        migrations.AddField(
            model_name='host',
            name='question_15_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Укажите дату '),
        ),
        migrations.AddField(
            model_name='host',
            name='question_16_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Условия установления даты'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_16_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Условия установления даты'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_17_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Страница Об условиях для гостей'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_17_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Страница Об условиях для гостей'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_18_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Страница подтверждения данных'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_18_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Страница подтверждения данных'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_1_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Тип услуги'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_1_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Тип услуги'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_2_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип кухни'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_2_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип кухни'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_3_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_3_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_4_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Дополнительные услуги'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_4_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Дополнительные услуги'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_5_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Доставка заказа'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_5_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Доставка заказа'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_6_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Соблюдение диеты'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_6_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Соблюдение диеты'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_7_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Аллергены'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_7_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Аллергены'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_8_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Гостей максимум'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_8_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Гостей максимум'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_9_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Гостей минимум'),
        ),
        migrations.AddField(
            model_name='host',
            name='question_9_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Гостей минимум'),
        ),
        migrations.AddField(
            model_name='host',
            name='title_descriptions_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание главной страницы'),
        ),
        migrations.AddField(
            model_name='host',
            name='title_descriptions_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание главной страницы'),
        ),
    ]
