# Generated by Django 4.2.7 on 2024-02-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_alter_host_options_chefregister'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chefregister',
            options={'verbose_name_plural': 'Заявки на регистрацию шефа'},
        ),
    ]
