# Generated by Django 4.2.7 on 2024-02-28 18:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_alter_host_question_8_alter_host_question_8_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='steps',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Шаги для клиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='steps_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Шаги для клиента'),
        ),
        migrations.AddField(
            model_name='host',
            name='steps_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Шаги для клиента'),
        ),
    ]
