# Generated by Django 4.2.7 on 2024-02-18 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('host', '0005_alter_chefregister_options_alter_host_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefregister',
            name='user_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chef_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chefregister',
            name='user_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chef_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
