# Generated by Django 4.2.7 on 2024-02-18 12:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0006_chefregister_user_en_chefregister_user_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefregister',
            name='user_en',
        ),
        migrations.RemoveField(
            model_name='chefregister',
            name='user_ru',
        ),
        migrations.AlterField(
            model_name='chefregister',
            name='question_12',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Напишите подробное описание объявления'),
        ),
        migrations.AlterField(
            model_name='chefregister',
            name='question_12_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Напишите подробное описание объявления'),
        ),
        migrations.AlterField(
            model_name='chefregister',
            name='question_12_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Напишите подробное описание объявления'),
        ),
    ]
