# Generated by Django 4.2.7 on 2024-02-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0007_blog_blogactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='becomeahost',
            name='image_end',
            field=models.ImageField(default=1, upload_to='becomeahost', verbose_name='Конечный фото'),
            preserve_default=False,
        ),
    ]
