# Generated by Django 4.2.7 on 2024-02-12 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_perfectactive_options_perfectactive_foreign'),
        ('host', '0009_pricefood'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricefood',
            options={'verbose_name_plural': 'Прием пищи'},
        ),
        migrations.RemoveField(
            model_name='pricefood',
            name='foreing',
        ),
        migrations.RemoveField(
            model_name='pricefood',
            name='perfect_active',
        ),
        migrations.AddField(
            model_name='pricefood',
            name='foreing_perfect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.perfectactive'),
            preserve_default=False,
        ),
    ]
