# Generated by Django 4.2.7 on 2024-02-12 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_perfectactive_options_perfectactive_foreign'),
        ('host', '0010_alter_pricefood_options_remove_pricefood_foreing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricefood',
            name='foreing_perfect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.perfect'),
        ),
    ]
