# Generated by Django 4.2.7 on 2024-02-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0011_alter_pricefood_foreing_perfect'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricefood',
            name='inline',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Brunch', 'Brunch'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default=1, max_length=155, verbose_name='Типы'),
            preserve_default=False,
        ),
    ]
