# Generated by Django 4.2.7 on 2024-02-13 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0012_pricefood_inline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceFood',
        ),
    ]
