# Generated by Django 4.2.7 on 2024-02-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0013_delete_pricefood'),
    ]

    operations = [
        migrations.AddField(
            model_name='becomeahost',
            name='descriptions2_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание Sing-in'),
        ),
        migrations.AddField(
            model_name='becomeahost',
            name='descriptions2_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание Sing-in'),
        ),
        migrations.AddField(
            model_name='becomeahost',
            name='descriptions3_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание reservation'),
        ),
        migrations.AddField(
            model_name='becomeahost',
            name='descriptions3_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание reservation'),
        ),
        migrations.AddField(
            model_name='becomeahost',
            name='descriptions4_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание guests'),
        ),
        migrations.AddField(
            model_name='becomeahost',
            name='descriptions4_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание guests'),
        ),
        migrations.AddField(
            model_name='becomeahost',
            name='descriptions_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='becomeahost',
            name='descriptions_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='becomeahost',
            name='image_en',
            field=models.ImageField(null=True, upload_to='becomeahost/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='becomeahost',
            name='image_end_en',
            field=models.ImageField(null=True, upload_to='becomeahost', verbose_name='Конечный фото'),
        ),
        migrations.AddField(
            model_name='becomeahost',
            name='image_end_ru',
            field=models.ImageField(null=True, upload_to='becomeahost', verbose_name='Конечный фото'),
        ),
        migrations.AddField(
            model_name='becomeahost',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='becomeahost/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='becomeahost',
            name='title2_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовок Выбора'),
        ),
        migrations.AddField(
            model_name='becomeahost',
            name='title2_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовок Выбора'),
        ),
        migrations.AddField(
            model_name='becomeahost',
            name='title3_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовка ХОЗЯИН'),
        ),
        migrations.AddField(
            model_name='becomeahost',
            name='title3_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовка ХОЗЯИН'),
        ),
        migrations.AddField(
            model_name='becomeahost',
            name='title4_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовок Sing-in'),
        ),
        migrations.AddField(
            model_name='becomeahost',
            name='title4_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовок Sing-in'),
        ),
        migrations.AddField(
            model_name='becomeahost',
            name='title5_en',
            field=models.CharField(max_length=155, null=True, verbose_name='заголовок reservation'),
        ),
        migrations.AddField(
            model_name='becomeahost',
            name='title5_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='заголовок reservation'),
        ),
        migrations.AddField(
            model_name='becomeahost',
            name='title6_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовок guests'),
        ),
        migrations.AddField(
            model_name='becomeahost',
            name='title6_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовок guests'),
        ),
        migrations.AddField(
            model_name='becomeahost',
            name='title_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='becomeahost',
            name='title_end_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовка Chef '),
        ),
        migrations.AddField(
            model_name='becomeahost',
            name='title_end_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовка Chef '),
        ),
        migrations.AddField(
            model_name='becomeahost',
            name='title_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='becomeend',
            name='descritions_en',
            field=models.CharField(max_length=355, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='becomeend',
            name='descritions_ru',
            field=models.CharField(max_length=355, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='becomeend',
            name='icon_en',
            field=models.CharField(choices=[('What does a publication include?', 'What does a publication include?'), ('Who can book my table?', 'Who can book my table?'), ('We’re here to help', 'We’re here to help'), ('Send messages to your guests', 'Send messages to your guests'), ('Organise a meeting after confirmation', 'Organise a meeting after confirmation'), ('Start with the essential', 'Start with the essential'), ('How do the guests pay?', 'How do the guests pay?'), ('How is done the wire-transfer to my account?', 'How is done the wire-transfer to my account?'), ('Homemeal fees', 'Homemeal fees'), ('How do I fix my fees?', 'How do I fix my fees?'), ('Homemeal insurance', 'Homemeal insurance'), ('Secured transactions', 'Secured transactions'), ('Trust and safety.', 'Trust and safety.'), ('So much more than money', 'So much more than money')], max_length=155, null=True, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='becomeend',
            name='icon_ru',
            field=models.CharField(choices=[('What does a publication include?', 'What does a publication include?'), ('Who can book my table?', 'Who can book my table?'), ('We’re here to help', 'We’re here to help'), ('Send messages to your guests', 'Send messages to your guests'), ('Organise a meeting after confirmation', 'Organise a meeting after confirmation'), ('Start with the essential', 'Start with the essential'), ('How do the guests pay?', 'How do the guests pay?'), ('How is done the wire-transfer to my account?', 'How is done the wire-transfer to my account?'), ('Homemeal fees', 'Homemeal fees'), ('How do I fix my fees?', 'How do I fix my fees?'), ('Homemeal insurance', 'Homemeal insurance'), ('Secured transactions', 'Secured transactions'), ('Trust and safety.', 'Trust and safety.'), ('So much more than money', 'So much more than money')], max_length=155, null=True, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='becomeend',
            name='title_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='becomeend',
            name='title_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='blog',
            name='descriptions_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='blog',
            name='descriptions_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_en',
            field=models.ImageField(null=True, upload_to='becomehost', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='becomehost', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовка'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовка'),
        ),
        migrations.AddField(
            model_name='blogactive',
            name='descriptions_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='blogactive',
            name='descriptions_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='blogactive',
            name='image_en',
            field=models.ImageField(null=True, upload_to='becomehost', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='blogactive',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='becomehost', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='blogactive',
            name='title_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовка'),
        ),
        migrations.AddField(
            model_name='blogactive',
            name='title_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовка'),
        ),
        migrations.AddField(
            model_name='free',
            name='descritions_en',
            field=models.CharField(max_length=355, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='free',
            name='descritions_ru',
            field=models.CharField(max_length=355, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='free',
            name='icon_en',
            field=models.CharField(choices=[('What does a publication include?', 'What does a publication include?'), ('Who can book my table?', 'Who can book my table?'), ('We’re here to help', 'We’re here to help'), ('Send messages to your guests', 'Send messages to your guests'), ('Organise a meeting after confirmation', 'Organise a meeting after confirmation'), ('Start with the essential', 'Start with the essential'), ('How do the guests pay?', 'How do the guests pay?'), ('How is done the wire-transfer to my account?', 'How is done the wire-transfer to my account?'), ('Homemeal fees', 'Homemeal fees'), ('How do I fix my fees?', 'How do I fix my fees?'), ('Homemeal insurance', 'Homemeal insurance'), ('Secured transactions', 'Secured transactions'), ('Trust and safety.', 'Trust and safety.'), ('So much more than money', 'So much more than money')], max_length=155, null=True, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='free',
            name='icon_ru',
            field=models.CharField(choices=[('What does a publication include?', 'What does a publication include?'), ('Who can book my table?', 'Who can book my table?'), ('We’re here to help', 'We’re here to help'), ('Send messages to your guests', 'Send messages to your guests'), ('Organise a meeting after confirmation', 'Organise a meeting after confirmation'), ('Start with the essential', 'Start with the essential'), ('How do the guests pay?', 'How do the guests pay?'), ('How is done the wire-transfer to my account?', 'How is done the wire-transfer to my account?'), ('Homemeal fees', 'Homemeal fees'), ('How do I fix my fees?', 'How do I fix my fees?'), ('Homemeal insurance', 'Homemeal insurance'), ('Secured transactions', 'Secured transactions'), ('Trust and safety.', 'Trust and safety.'), ('So much more than money', 'So much more than money')], max_length=155, null=True, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='free',
            name='title_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='free',
            name='title_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='guests',
            name='descritions_en',
            field=models.CharField(max_length=355, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='guests',
            name='descritions_ru',
            field=models.CharField(max_length=355, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='guests',
            name='icon_en',
            field=models.CharField(choices=[('What does a publication include?', 'What does a publication include?'), ('Who can book my table?', 'Who can book my table?'), ('We’re here to help', 'We’re here to help'), ('Send messages to your guests', 'Send messages to your guests'), ('Organise a meeting after confirmation', 'Organise a meeting after confirmation'), ('Start with the essential', 'Start with the essential'), ('How do the guests pay?', 'How do the guests pay?'), ('How is done the wire-transfer to my account?', 'How is done the wire-transfer to my account?'), ('Homemeal fees', 'Homemeal fees'), ('How do I fix my fees?', 'How do I fix my fees?'), ('Homemeal insurance', 'Homemeal insurance'), ('Secured transactions', 'Secured transactions'), ('Trust and safety.', 'Trust and safety.'), ('So much more than money', 'So much more than money')], max_length=155, null=True, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='guests',
            name='icon_ru',
            field=models.CharField(choices=[('What does a publication include?', 'What does a publication include?'), ('Who can book my table?', 'Who can book my table?'), ('We’re here to help', 'We’re here to help'), ('Send messages to your guests', 'Send messages to your guests'), ('Organise a meeting after confirmation', 'Organise a meeting after confirmation'), ('Start with the essential', 'Start with the essential'), ('How do the guests pay?', 'How do the guests pay?'), ('How is done the wire-transfer to my account?', 'How is done the wire-transfer to my account?'), ('Homemeal fees', 'Homemeal fees'), ('How do I fix my fees?', 'How do I fix my fees?'), ('Homemeal insurance', 'Homemeal insurance'), ('Secured transactions', 'Secured transactions'), ('Trust and safety.', 'Trust and safety.'), ('So much more than money', 'So much more than money')], max_length=155, null=True, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='guests',
            name='title_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='guests',
            name='title_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='receive',
            name='descritions_en',
            field=models.CharField(max_length=355, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='receive',
            name='descritions_ru',
            field=models.CharField(max_length=355, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='receive',
            name='icon_en',
            field=models.CharField(choices=[('What does a publication include?', 'What does a publication include?'), ('Who can book my table?', 'Who can book my table?'), ('We’re here to help', 'We’re here to help'), ('Send messages to your guests', 'Send messages to your guests'), ('Organise a meeting after confirmation', 'Organise a meeting after confirmation'), ('Start with the essential', 'Start with the essential'), ('How do the guests pay?', 'How do the guests pay?'), ('How is done the wire-transfer to my account?', 'How is done the wire-transfer to my account?'), ('Homemeal fees', 'Homemeal fees'), ('How do I fix my fees?', 'How do I fix my fees?'), ('Homemeal insurance', 'Homemeal insurance'), ('Secured transactions', 'Secured transactions'), ('Trust and safety.', 'Trust and safety.'), ('So much more than money', 'So much more than money')], max_length=155, null=True, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='receive',
            name='icon_ru',
            field=models.CharField(choices=[('What does a publication include?', 'What does a publication include?'), ('Who can book my table?', 'Who can book my table?'), ('We’re here to help', 'We’re here to help'), ('Send messages to your guests', 'Send messages to your guests'), ('Organise a meeting after confirmation', 'Organise a meeting after confirmation'), ('Start with the essential', 'Start with the essential'), ('How do the guests pay?', 'How do the guests pay?'), ('How is done the wire-transfer to my account?', 'How is done the wire-transfer to my account?'), ('Homemeal fees', 'Homemeal fees'), ('How do I fix my fees?', 'How do I fix my fees?'), ('Homemeal insurance', 'Homemeal insurance'), ('Secured transactions', 'Secured transactions'), ('Trust and safety.', 'Trust and safety.'), ('So much more than money', 'So much more than money')], max_length=155, null=True, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='receive',
            name='title_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='receive',
            name='title_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Заголовок'),
        ),
    ]
